### ISSUE TITLE
Autoincrement is broken; consultation needed on how to fix

### ISSUE THREAD

**Issue by NocturnalSolutions** [IBM-Swift/Swift-Kuery-SQLite#18]
From SQLiteConnection:

```swift
    static func createAutoIncrement(_ type: String, _ primaryKey: Bool) -> String {
        if primaryKey && type == "integer" {
            return type + "AUTOINCREMENT"
        } else {
            return ""
        }
    }
```

There's no space before `AUTOINCREMENT`, so the resulting field type looks like "integerAUTOINCREMENT". Hilariously, SQLite don't care and dutifully creates a column with an integerAUTOINCREMENT type.

```
sqlite> .schema posts
CREATE TABLE IF NOT EXISTS "posts" ("id" integerAUTOINCREMENT PRIMARY KEY, "date" varchar(19) NOT NULL);
```

Unfortunately, fixing this isn't as easy as just adding that space back in, because the proper syntax for an autoincrement field is actually `integer PRIMARY KEY AUTOINCREMENT`. But if you define the field you want to autoincrement as a primary key, then it comes out as `integer PRIMARY KEY AUTOINCREMENT PRIMARY KEY`, and SQLite doesn't like since it thinks we're trying to create multiple primary keys. (Or, if you instantiate the table class and try creating a primary key using the `primaryKey` method, you get `CREATE TABLE…("id" integer PRIMARY KEY AUTOINCREMENT…) PRIMARY KEY ("id")` which SQLite also can't handle.)

Possible solutions:

1. Tweak the `createAutoIncrement` code to ignore the primaryKey state of the field, so it'd be something like:
```swift
    static func createAutoIncrement(_ type: String, _ primaryKey: Bool) -> String {
        return type == "integer" ? "integer PRIMARY KEY AUTOINCREMENT" : ""
    }
```
and then tell users to not define the relevant field as a primary key in their schema code. This will break cross-compatibility with other Kuery implementations, I'm pretty sure, but it wouldn't require (further hacking to) the core Kuery project.

2. Just as it has a `createAutoIncrement` method, implement a `createPrimaryKey` method on the  `QueryBuilder` class and implement it in Swift-Kuery-SQLite with something like:
```swift
    static func createPrimaryKey(_ type: String, _ isAutoIncrement: Bool) -> String {
        return isAutoIncrement ? "" : "PRIMARY KEY";
    }
```
Then also do the tweak to `createAutoIncrement`. This would be a better approach quality-of-code-wise, but requires hacking the core Kuery project.

3. Anyone have any better ideas?

**Comment by kilnerm** [comment]
There is no way to fix this without changing the core Kuery project as it currently builds the create query in the order:

- type + auto increment?
- primary key

this will need changing to add the type and the primary key before the optional auto increment and then the SQLite createPrimaryKey method will need updating to not add the type.

The new query syntax will need checking against the other databases Kuery supports to ensure it is compatible.

**Comment by NocturnalSolutions** [comment]
> this will need changing to add the type and the primary key before the optional auto increment and then the SQLite createPrimaryKey method will need updating to not add the type.

It seems the reason it was done this way was to accommodate Postgres, for which the syntax of an auto-increment column is like `id SERIAL PRIMARY KEY`. So the type gets munged to SERIAL but there's no "AUTOINCREMENT" (or "AUTO_INCREMENT"). So in this case, it *is* necessary that the code that handles the auto-increment case runs before the primary key suffix code as the query string is built from start to end.

This is why I think having a method the database driver can implement to override how the PRIMARY KEY bit is added to the string the same way it's done for auto-incrementation might be the cleanest approach.

I think I'll go ahead and see if I can get this implemented and make a Kuery PR.

**Comment by kilnerm** [comment]
I have pulled together an alternate solution and raised the appropriate PR's:

https://github.com/IBM-Swift/SwiftKueryMySQL/pull/32
https://github.com/IBM-Swift/Swift-Kuery-SQLite/pull/21

By offloading to the plugin we will avoid hitting syntax differences in future.

**Comment by kilnerm** [comment]
This is now merged into the next branches of SwiftKuery and the plugins.
