### ISSUE TITLE
Restrict autoincrement column type to Int / Int64

### ISSUE THREAD

**Issue by kilnerm** [IBM-Swift/Swift-Kuery-SQLite#25]
When defining a column as autoincrement primarykey SQLite creates an alias for its internal ROWID column. 

The ROWID column is always stored as an 8 byte integer.

If we allow an autoincrement primary key column to be defined as smaller integer type it is possible that an overflow can occur.

**Comment by GarrettAlbright** [comment]
> The ROWID column is always stored as an 8 byte integer.

Sorry to um actually, but um, actually, ROWID is a [64-bit signed integer](https://www.sqlite.org/autoinc.html).

> If we allow an autoincrement primary key column to be defined as smaller integer type it is possible that an overflow can occur.

SQLite won't allow this, though. The only syntax that can create an autoincrement column is `INTEGER PRIMARY KEY AUTOINCREMENT`. Trying to create an autoincrement column with some other integer type doesn't work.

```
sqlite> CREATE TABLE baz ( qux TINYINT PRIMARY KEY AUTOINCREMENT );
Error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
```

**Comment by NocturnalSolutions** [comment]
> The ROWID column is always stored as an 8 byte integer.

Sorry to um actually, but um, actually, ROWID is a [64-bit signed integer](https://www.sqlite.org/autoinc.html).

EDIT: And 64 bits is 8 bytes. Sorry, I'm an idiot.

> If we allow an autoincrement primary key column to be defined as smaller integer type it is possible that an overflow can occur.

SQLite won't allow this, though. The only syntax that can create an autoincrement column is `INTEGER PRIMARY KEY AUTOINCREMENT`. Trying to create an autoincrement column with some other integer type doesn't work.

```
sqlite> CREATE TABLE baz ( qux TINYINT PRIMARY KEY AUTOINCREMENT );
Error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
```

**Comment by kilnerm** [comment]
Currently the SQLite plugin requires you to use Int32 for a column type you want to manually define as autoincrement. 

Because SQLite isn't strongly typed the actual storage class that is used for the column is Integer so if I insert a row using the id INT32_MAX into the column and then insert a row allowing the column to autoincrement the second insert gets an id of 1 greater then my defined column type can store (but that can be stored in the db). If you try to read this id back into an Int32 you get an incorrect value.

As a side issue the plugin does not currently allow you to retrieve any bigint values due to the underlying SQLite C api used. I have looked to see if we can determine the column type beyond the integer storage class and have not found an API to allow this, so when retrieving a value from a column we do not have a means to determine the original type stored. This will be particularly problematic for the SwiftKuery ORM.

This is a particularly horrible problem to solve.

This relates to issue #26

**Comment by kilnerm** [comment]
My proposal here is in two parts:

1) When declaring a column as integer and primary key the column will require the Int64 type. Any other type will be rejected.

2) If a table is defined with type information I will use the declaration to ensure the retrieved value is correctly typed. If no type information is available then we will retrieve all integers as 64 bit by default, user code will need to handle this correctly.

**Comment by kilnerm** [comment]
Having looked our our options here I feel the best solution is to simply reject any integer types other than Int64.

To determine types at fetch time would require us to parse every raw query string and build a dictionary of columns to type (including handling cases where columns are requested across multiple tables). The overhead of doing this is likely to be detrimental to the performance of all Select queries.

I also considered the option of returning a new datatype including both 32 and 64 bit values but that would not fit well with the SwiftKueryORM.

**Comment by kilnerm** [comment]
This is now merged.
