### ISSUE TITLE
Missing required module 'CSQLiteDarwin'?

### ISSUE THREAD

**Issue by diuming** [IBM-Swift/Swift-Kuery-SQLite#30]
I want to use `SwiftKuerySQLite` framework on macOS. so, I compile it in Xcode 10, everything looks well.
But When I `import` it. I got a warning `Missing required module 'CSQLiteDarwin'`.
I don't have any ideas for this issue, could you help me? please!

![sqlite](https://user-images.githubusercontent.com/39903550/48535550-b4e79c80-e8e6-11e8-8244-3446348d95d0.png)

**Comment by kilnerm** [comment]
CSQLiteDarwin is the name of the module that Swift will synthesize from the module.map file which should be contained in your SwiftKuerySQLite package under sources/CSQLite/include/.

Could I see the contents of the Package.swift file for both your project and the embedded SwiftKuerySQLite package please?

The other thing worth checking is that the SQLite headers are in the location expected in the module.map file mentioned previously, could you check the expected location matches the actual location please?

**Comment by diuming** [comment]
@kilnerm 
thanks for replying.
I compile sqlite3 from source then install to custom path.
so, I modify header to custom path in module.map, following

```
module CSQLiteDarwin [system] {
    header "/the/custom/path/for/sqlite3.h"
    link "sqlite3"
    export *
}
```

**Comment by diuming** [comment]
Note
---
![sqlite](https://user-images.githubusercontent.com/39903550/48557594-23961b80-e922-11e8-859c-99c950ed7d28.png)

Package.swift
---
```
import PackageDescription

let package = Package(
    name: "IBMSQLite",
    products: [
        .library(
            name: "IBMSQLite", targets: ["IBMSQLite"]),
    ],
    dependencies: [
        .package(url: "https://github.com/IBM-Swift/Swift-Kuery-SQLite.git", from: "1.1.0")
    ],
    targets: [
        .target(
            name: "IBMSQLite", dependencies: ["SwiftKuerySQLite"]),
        .testTarget(
            name: "IBMSQLiteTests", dependencies: ["IBMSQLite"]),
    ]
)
```

**Comment by kilnerm** [comment]
I think the issue lays somewhere in how you are using the package, this is certainly not a usage pattern I have seen before.

Are you able to import IBMSQLite instead of SwiftKuerySQLite?

I would normally expect SwiftKuerySQLite to be added as a dependency to the applications Package.swift file. Does this pattern not work for your application?

**Comment by diuming** [comment]
@kilnerm 
thank you for taking the time and help me with this issue.
I can not import `IBMSQLite`, please following, thanks!
![sqlite](https://user-images.githubusercontent.com/39903550/48659667-9a9cf280-ea8f-11e8-85ad-2c88c9785bbf.png)
![link](https://user-images.githubusercontent.com/39903550/48659679-e2237e80-ea8f-11e8-906e-cdd1b3858a4a.png)

**Comment by kilnerm** [comment]
Thanks for trying that out.

Could you try building the application from the command line using the "swift build" command?

My guess is that the missing module is failing to compile and I am hoping the console output may give some clues as to why.

**Comment by diuming** [comment]
@kilnerm 
My application is created by Xcode, so I can't use "swift build" command, sorry I did't mention it.
Finally! I find a workaround that just create a own module.modulemap for this application.
it is the same as `CSQLite's module.modulemap`
thank you for help.

**Comment by kilnerm** [comment]
Marking as closed
